#!/bin/bash

script=$1

# If the actual script exists, and
if [ -e scripts/$script ]; then

    # echo "Target $script exists"

    # if it is newer than the "cooked" version, or the cooked version
    # does not exist, we add in the SGML source, producing the cooked
    # version.

    if [ scripts/$script -nt cooked/$script ] || [ ! -e cooked/$script ] ; then

	echo "rebuilding $script"
	echo -n '<![ CDATA [' > cooked/$script
	cat scripts/$script >> cooked/$script
	echo ']]>' >> cooked/$script

    fi
fi
